create database leetcode178;
use leetcode178;
create table Scores(Id int,Score dec(3,2));
insert into Scores values(1,3.50);
insert into Scores values(2,3.65);
insert into Scores values(3,4.00);
insert into Scores values(4,3.85);
insert into Scores values(5,4.00);
insert into Scores values(6,3.65);
select * from Scores;
select * from Scores order by Score desc;
select min(Scores.score) Score,count(*) Rank from Scores,(select distinct Score from Scores) ranking where Scores.score<=ranking.score group by Scores.Id order by Score desc;